#ifndef PLAYERBOTS_STATEMENTS_H
#define PLAYERBOTS_STATEMENTS_H

enum PlayerbotsDatabaseStatements
{
    PLAYERBOTS_SEL_TEXT,

    // Invite Code System
    PLAYERBOTS_SEL_INVITE_CODES_COUNT,
    PLAYERBOTS_INS_INVITE_CODE,
    PLAYERBOTS_SEL_INVITE_CODE_VALID,
    PLAYERBOTS_SEL_INVITE_CODE_EXISTS_ANY,
    PLAYERBOTS_SEL_LINK_EXIST,
    PLAYERBOTS_INS_ACCOUNT_LINK,
    PLAYERBOTS_SEL_INVITE_CODES_BY_ACCOUNT,
    PLAYERBOTS_SEL_INVITE_CODE_BY_CODE,
    PLAYERBOTS_UPD_INVITE_CODE_REVOKE,

    // Account Management
    PLAYERBOTS_SEL_LINKED_ACCOUNTS,
    PLAYERBOTS_SEL_LINK_BY_SHORTNAME,
    PLAYERBOTS_DEL_ACCOUNT_LINK,

    // Cleanup
    PLAYERBOTS_DEL_EXPIRED_INVITE_CODES,

    MAX_PLAYERBOTS_DATABASE_STATEMENTS
};

#endif
